eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
      
microservice:
  payments:
    endpoints:
      endpoint:
        uri: http://PAYMENTS/payment/doPayment
  orders:
    endpoints:
      endpoint:
        uri: http://ORDERS/order/bookOrder      
